/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useEffect, useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { Material } from 'three'

export default function Pear(props: any) {
  const group = useRef()
  const { nodes, materials } = useGLTF('https://market-assets.fra1.cdn.digitaloceanspaces.com/market-assets/models/pear/model.gltf') as any

  useEffect(() => {
    Object.values(materials).forEach((material: Material) => {
      ;(material as any).metalness = 0.5
    })
  }, [])

  return (
    <group ref={group} {...props} dispose={null}>
      <mesh geometry={nodes.Mesh_pear.geometry} material={materials.green} />
      <mesh geometry={nodes.Mesh_pear_1.geometry} material={materials.brown} />
    </group>
  )
}

useGLTF.preload('https://market-assets.fra1.cdn.digitaloceanspaces.com/market-assets/models/pear/model.gltf')
